export const mockData = {
  city: {
    lat: 53.757607,
    lon: 87.136101,
    timezone: 'Asia/Novokuznetsk',
    timezone_offset: 25200,
    current: {
      dt: 1655735435,
      sunrise: 1655674815,
      sunset: 1655736336,
      temp: 17.38,
      feels_like: 17.47,
      pressure: 1004,
      humidity: 88,
      dew_point: 15.37,
      uvi: 0,
      clouds: 77,
      visibility: 10000,
      wind_speed: 0.87,
      wind_deg: 165,
      wind_gust: 0.87,
      weather: [
        {
          id: 803,
          main: 'Clouds',
          description: 'broken clouds',
          icon: '04d',
        },
      ],
    },
    name: 'Novokuznetsk',
    local_names: {
      en: 'Novokuznetsk',
      ko: '노보쿠즈네츠크',
      feature_name: 'Novokuznetsk',
      et: 'Novokuznetsk',
      ascii: 'Novokuznetsk',
      fr: 'Novokouznetsk',
      ro: 'Novokuznețk',
      cs: 'Novokuzněck',
      ar: 'نوفوكوزنتسك',
      lt: 'Novokuzneckas',
      pl: 'Nowokuźnieck',
      ja: 'ノヴォクズネツク',
      ru: 'Новокузнецк',
      zh: '新库兹涅茨克',
      de: 'Nowokusnezk',
      uk: 'Новокузнецьк',
      hr: 'Novokuznjeck',
      fi: 'Novokuznetsk',
    },
    country: 'RU',
    state: 'Kemerovo Oblast–Kuzbass',
    hourly: [
      {
        dt: 1655737200,
        temp: 14.43,
        feels_like: 288.44,
        pressure: 1038,
        humidity: 93,
        dew_point: 287.31,
        uvi: 8.03,
        clouds: 8,
        visibility: 10000,
        wind_speed: 4.62,
        wind_deg: 284,
        wind_gust: 6.68,
        weather: [
          {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01d',
          },
        ],
        pop: 0,
      },
      {
        dt: 1655740800,
        temp: 15.44,
        feels_like: 288.45,
        pressure: 1038,
        humidity: 93,
        dew_point: 287.32,
        uvi: 6.83,
        clouds: 8,
        visibility: 10000,
        wind_speed: 4.3,
        wind_deg: 296,
        wind_gust: 6.17,
        weather: [
          {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01d',
          },
        ],
        pop: 0,
      },
    ],
  },
  loading: false,
  onCardClick: jest.fn,
  onDeleteCity: jest.fn,
  onUpdateCityInfo: jest.fn,
  refreshLoading: false,
  updatingCity: '',
};
